first code to git
logzio/logzio-app-metrics pull request #1
Opened 2021-06-02 14:21 UTC by ShiranAvidov

initial commit

2021-06-28 18:13 UTC, Doron-Bargo commented on src/Core/Formatter/MetricsLogzioOutputFormatter.cs
> +        private void AddTimesSeriesToWriteRequest<T, S>(MetricTimeSeriesMapper<T, S> metricTimeSeriesMapper,
what are the performance of this function because it looks like you are running on each metrics and then run on them again

2021-06-28 18:38 UTC, Doron-Bargo requested changes
Amazing work
Lets talk on the comment i wrote

2021-06-28 18:38 UTC, Doron-Bargo commented on src/Core/Mapper/ApdexMetricTimeSeriesMapper.cs
> +        public ApdexMetricTimeSeriesMapper(ApdexValueSource apdexMetric, string context) : base(apdexMetric, context)
why we need this?

2021-06-28 18:38 UTC, Doron-Bargo commented on src/Core/Reporter/MetricsLogzioReporterBuilder.cs
> +            if (metricReporterProviderBuilder == null)
this part is retuning for all the functions - please move it to a private function

2021-06-28 18:38 UTC, Doron-Bargo commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportOptions_Success()
please add negative test

2021-06-28 18:38 UTC, Doron-Bargo commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportConfig_Success()
please add negative test

2021-06-28 18:38 UTC, Doron-Bargo commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportConfigWithTimespan_Success()
please add negative test

2021-06-28 18:38 UTC, Doron-Bargo commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportStrings_Success()
please add negative test

2021-07-01 10:08 UTC, ShiranAvidov commented on src/Core/Formatter/MetricsLogzioOutputFormatter.cs
> +        private void AddTimesSeriesToWriteRequest<T, S>(MetricTimeSeriesMapper<T, S> metricTimeSeriesMapper,
The performance is basically the number of metrics you have in the metrics builder.
The clients can give context to each metric (sort of a name tag to identify group of metrics). The first foreach goes over each context and inside looks for each metric type and takes their values which is finite.

2021-07-01 10:15 UTC, ShiranAvidov commented on src/Core/Mapper/ApdexMetricTimeSeriesMapper.cs
> +        public ApdexMetricTimeSeriesMapper(ApdexValueSource apdexMetric, string context) : base(apdexMetric, context)
If metric has more than one value, I create TimeSeries for each with the name of the metric and at the end the name of the value. In Logz.io you will be able to search per value by typing the metric name with value name (for example: myMetric_sample_size)

2021-07-05 09:02 UTC, ShiranAvidov commented on src/Core/Mapper/ApdexMetricTimeSeriesMapper.cs
> +        public ApdexMetricTimeSeriesMapper(ApdexValueSource apdexMetric, string context) : base(apdexMetric, context)
If you meant the Apdex in general, it's a metric that measures satisfaction. The client can measure satisfaction of one of their features. It's an App Metrics supported metric, so why not :)

2021-07-05 09:03 UTC, ShiranAvidov commented on src/Core/Reporter/MetricsLogzioReporterBuilder.cs
> +            if (metricReporterProviderBuilder == null)
Done

2021-07-05 09:03 UTC, ShiranAvidov commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportOptions_Success()
Done

2021-07-05 09:03 UTC, ShiranAvidov commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportConfig_Success()
Done

2021-07-05 09:03 UTC, ShiranAvidov commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportConfigWithTimespan_Success()
Done

2021-07-05 09:03 UTC, ShiranAvidov commented on src/UnitTests/CreatingMetricsBuilderTests.cs
> +        public void Create_WithReportStrings_Success()
Done

2021-07-11 12:25 UTC, Doron-Bargo approved these changes
Amazing work!!!!

2021-07-14 09:00 UTC, merged